[package]
name = "meme_connect"
version = "0.1.0"
authors = ["InNoobWeTrust"]
edition = "2021"

[workspace]
members = [
    "board",
    "ui",
]

[dependencies]
board = { path = "./board" }
ui = { path = "./ui" }
macroquad = "^0.4"

[profile.dev.package.'*']
opt-level = 3
