[package]
name = "meme_connect"
version = "0.1.0"
authors = ["InNoobWeTrust"]
edition = "2018"

[workspace]
members = [
    "core",
    "ui",
]

[dependencies]
core = { path = "./core" }
ui = { path = "./ui" }
macroquad = "0.2.9"
