[package]
name = "meme_connect"
version = "0.1.0"
authors = ["InNoobWeTrust"]
edition = "2018"

[[bin]]
name = "meme_connect"
path = "src/main.rs"

[lib]
name = "meme_connect"
path = "src/lib.rs"

[dependencies]
rand = "0.7.3"
